pipeline:
  build_push_to_ecr:
    image: plugins/ecr:latest
    secrets:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    enviroment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    - AWS_REGION=eu-west-2
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/base
    privileged: false
    tags:
    - ${DRONE_TAG}
