pipeline:
  build_push_to_ecr:
    image: plugins/ecr
    secrets:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/base
    privileged: false
    tags:
    - ${DRONE_TAG}
